name = "TestJiveFailFast"
uuid = "c5948fb1-314b-4d22-bcf9-e98965e89a9e"
authors = ["WooKyoung Noh <wookay.noh@gmail.com>"]
version = "0.1.0"

[compat]
Jive = "0.3"
julia = "1.6"

[extras]
Jive = "ba5e3d4b-8524-549f-bc71-e76ad9e9deed"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Jive"]
